baseURL = 'https://delroth.net/'
theme = ['poison', 'hugo-shortcode-gallery']
languageCode = 'en-us'
pluralizelisttitles = false
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "delroth's homepage"
custom_css = ["css/custom.css"]

[author]
  name = "delroth"

[params]
  brand = "delroth's homepage"
  brand_image = "/images/avatar.png"
  favicon = "/images/avatar.png"
  description = "Infosec, travel, hiking, gaming, anime, and everything else in my life"
  dark_mode = true

  mastodon_url = "https://mastodon.delroth.net/@delroth"
  github_url = "https://github.com/delroth"
  linkedin_url = "https://www.linkedin.com/in/delrothh/"
  email_url = "mailto:delroth@gmail.com"

  rss_icon = true
  rss_section = "posts"

  menu = [
    {Name = "About me", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 3},
    {Name = "Website source code", URL = "https://github.com/delroth/delroth.net", External = true, HasChildren = false},
  ]

  code_color_dark = "#ff9f9f"
  list_color_dark = "#ccc"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
